## Local

server:
  port: 9898


# Auto Reload
spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    cache: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kyeong

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/daisy?useUnicode=yes&characterEncoding=UTF-8
    username: root
    password: "aabb1595"
